/* =====================================================================
   strings.js – alle sichtbaren Texte in de, en, es, fr, tr.
   Vor app.js geladen. Stellt bereit:
     tr(key, vars)   – übersetzter Text mit {platzhaltern}
     trp(key, n, vars) – Pluralform (one/other)
     lang() / setLang(code)
     SPRACHEN, SPRACH_NAME
   ===================================================================== */
"use strict";

const SPRACHEN = ["de", "en", "es", "fr", "tr"];
const SPRACH_NAME = {
  de: "Deutsch", en: "English", es: "Español", fr: "Français", tr: "Türkçe"
};

const I18N = {
  de: {
    "title": "Rechen-Ritter – Plus und Minus bis 20",
    "start.titel": "Rechen-Ritter",
    "start.untertitel": "Rechnen wird zum Abenteuer",
    "wer.spielt": "Wer spielt?",
    "konto.tippe": "Tippe auf dein Bild.",
    "dein.rang": "Dein Rang",
    "frage.raum": "Wie weit rechnen wir?",
    "frage.art": "Was üben wir?",
    "raum.bis10": "bis 10",
    "raum.bis20": "bis 20",
    "art.plus": "nur Plus",
    "art.beides": "Plus und Minus",
    "wahl.ausgewaehlt": "✓ ausgewählt",
    "konto.du.bist.dran": "✓ du bist dran",
    "spielen.verdienen": "🎯 Spielen & Verdienen",
    "gold.ausgeben": "🪙 Gold ausgeben",
    "badge.verdienen": "Verdienen",
    "badge.ausgeben": "Ausgeben",
    "badge.ansehen": "Ansehen",
    "ton.an": "🔊 Ton an",
    "ton.aus": "🔇 Ton aus",
    "ton.kurz": "🔊 Ton",
    "heim": "🏠 Auswahl",
    "kammer": "🗝️ Schatzkammer",
    "tipp": "💡 Tipp",
    "gold": "Gold",
    "serie": "Serie",
    "aufgabe": "Aufgabe",
    "puzzle": "Puzzle",
    "teile": "Teile",
    "mauer": "Mauer",
    "turm": "Turm",
    "gegner": "Gegner",
    "futter": "Futter",
    "drache": "Drache",
    "burgwert": "Burgwert",
    "bilder": "Bilder",
    "zurueck": "Zurück",

    "schatz.diamant": "Diamant",
    "schatz.krone": "Krone",
    "schatz.schluessel": "Goldschlüssel",
    "schatz.stab": "Zauberstab",
    "schatz.schwert": "Flammenschwert",
    "schatz.schild": "Silberschild",
    "schatz.ei": "Drachenei",
    "schatz.einhorn": "Einhorn",
    "schatz.kompass": "Kompass",
    "schatz.laterne": "Ewiges Licht",
    "schatz.vase": "Goldvase",
    "schatz.perle": "Regenbogenperle",
    "galerie.kurz": "🖼️ Galerie",
    "puzzle.kurz": "🧩 Puzzle",

    "karte.kampf.titel": "Ritter gegen Drachen",
    "karte.kampf.text": "Schlag dem Drachen die Giftzähne aus. Jeder Treffer bringt Gold.",
    "karte.hort.titel": "Schatzjagd",
    "karte.hort.text": "Sammle Gold in Ruhe – ohne Herzen, ohne Verlieren.",
    "karte.mauer.titel": "Rechenmauer",
    "karte.mauer.text": "Fülle die Lücken der Zahlenmauer und verdiene Gold.",
    "karte.turnier.titel": "Ritter-Turnier",
    "karte.turnier.text": "Stich mit deiner Lanze zu – rechne dich bis zum Gegner vor.",
    "karte.turm.titel": "Drachenturm",
    "karte.turm.text": "Steig die Leiter hinauf zum Schatz \u2013 und wieder hinunter.",
    "karte.uhr.titel": "Uhrturm",
    "karte.uhr.text": "Lies die Turmuhr ab, damit die Glocke wieder l\u00e4utet.",
    "karte.puzzle.titel": "Puzzle-Schatz",
    "karte.puzzle.text": "Kaufe Puzzleteile für 200 Gold und enthülle das Bild Stück für Stück.",
    "karte.galerie.titel": "Bildergalerie",
    "karte.galerie.text": "Schau dir alle Bilder an, die du schon gelöst hast.",
    "karte.burg.titel": "Burg bauen",
    "karte.burg.text": "Gib Gold aus und errichte deine Burg Stein für Stein.",
    "karte.hoehle.titel": "Drachenhöhle",
    "karte.hoehle.text": "Kauf ein Drachenei und zieh deinen eigenen Drachen gross.",

    "rang.knappe": "Knappe",
    "rang.ritter": "Ritter",
    "rang.schatzmeister": "Schatzmeister",
    "rang.drachenreiter": "Drachenreiter",
    "rang.legende": "Legende",
    "rang.baron": "Baron",
    "rang.graf": "Graf",
    "rang.herzog": "Herzog",
    "rang.fuerst": "Fürst",
    "rang.koenig": "König",
    "rang.kaiser": "Kaiser",
    "rang.drachentoeter": "Drachentöter",
    "rang.unsterblicher": "Unsterblicher",
    "rang.gott.des.goldes": "Gott des Goldes",
    "rang.fortschritt": "noch {n} bis {rang}",
    "rang.max": "Höchster Rang erreicht! 🌠",
    "rang.neu": "Neuer Rang!",

    "drache.glutzahn": "Glutzahn",
    "drache.nebelschwinge": "Nebelschwinge",
    "drache.frostkralle": "Frostkralle",
    "drache.schattenhorn": "Schattenhorn",
    "drache.koenigsdrache": "Königsdrache",

    "k.partei.ritter": "Ritter",
    "k.runde": "Drache {n}/{m}",
    "frage.zahl": "Welche Zahl passt?",
    "k.falsch": "Richtig wäre: {loesung}",
    "k.falsch.gold": "Richtig wäre: {loesung}  −{n} Gold",
    "k.win.titel": "{name} ist besiegt!",
    "k.win.beute": "🪙 +{n} Gold Drachenschatz",
    "k.win.text": "Weiter geht's: {name} wartet schon. Deine Herzen sind wieder voll.",
    "k.ende.sieg.titel": "Alle Drachen besiegt!",
    "k.ende.sieg.text": "Das Königreich ist gerettet – und dein Drachengold liegt in der Schatzkammer.",
    "k.ende.niederlage.titel": "Der Drache war stärker",
    "k.ende.niederlage.text": "Deine Herzen sind aufgebraucht. Dein Gold bleibt dir – noch ein Versuch?",

    "lob.treffer": "Treffer!",
    "lob.stark": "Stark!",
    "lob.volltreffer": "Volltreffer!",
    "lob.genau": "Genau richtig!",
    "lob.perfekt": "Perfekt!",
    "lob.super": "Super gerechnet!",

    "gold.plus": "+{n} Gold",

    "h.fast": "Fast! {loesung} – gleich nochmal.",
    "h.fast.gold": "Fast! {loesung}  −{n} Gold. Gleich nochmal.",
    "h.serie": "🔥 Serie! Ab jetzt ×{n} Gold",
    "h.ziel.basis": { one: "{n} Aufgabe geschafft, beste Serie: {b}.", other: "{n} Aufgaben geschafft, beste Serie: {b}." },
    "h.ziel.sauber": "Und kein einziger Fehler!",
    "h.weiterso": "Weiter so!",

    "puzzle.kaufen": "🧩 Puzzleteil kaufen – {n} Gold",
    "puzzle.eins": "🧩 1 Puzzleteil",
    "puzzle.rest": { one: "{n} Teil fehlt noch. Mit jedem Kauf wird das Bild sichtbarer.", other: "{n} Teile fehlen noch. Mit jedem Kauf wird das Bild sichtbarer." },
    "puzzle.brauchst": "Du brauchst noch {n} Gold.",
    "puzzle.genug": "Du hast genug Gold – welches Stück wird als Nächstes sichtbar?",
    "puzzle.alle.btn": "🏆 Alle Bilder gesammelt!",
    "puzzle.alle.text": "Geschafft! Du hast jedes Bild vollständig enthüllt.",
    "puzzle.alle.hinweis": "In der Bildergalerie kannst du sie dir alle ansehen.",
    "puzzle.geloest.btn": "🏆 Puzzle gelöst!",
    "puzzle.geloest.text": "Geschafft! Das Bild ist vollständig enthüllt.",
    "puzzle.geloest.hinweis": "Das nächste Puzzle wird vorbereitet …",
    "puzzle.funken": "🎉 Puzzle gelöst!",
    "puzzle.wandert": "Es wandert in die Bildergalerie – das nächste Abenteuer wartet!",
    "puzzle.alle.galerie": "Alle Bilder hängen jetzt in deiner Bildergalerie!",

    "galerie.titel": "🖼️ Deine Bildergalerie",
    "galerie.leer": "Noch kein Bild fertig – löse ein Puzzle, dann hängt es hier.",
    "galerie.alle": "Alle {n} Bilder gesammelt! Tippe eines an.",
    "galerie.teile": { one: "{n} von {m} Bild fertig. Tippe es an.", other: "{n} von {m} Bildern fertig. Tippe eines an." },
    "galerie.teile.kurz": "{n}/{m} Teile",
    "galerie.noch.zu": "noch zu",
    "bild.titel": "Bild {n}",
    "bild.hinweis": "Tippe das Bild an, um es grösser zu sehen.",
    "bild.zoom": "Schieb mit dem Finger über das Bild. Nochmal tippen macht es wieder klein.",

    "burg.teil.mauer": "Mauer",
    "burg.teil.rote-mauer": "Backstein",
    "burg.teil.turmstein": "Turmstein",
    "burg.teil.tor": "Tor",
    "burg.teil.fenster": "Fenster",
    "burg.teil.dach": "Dach",
    "burg.teil.flagge": "Flagge",
    "burg.teil.wappen": "Wappen",
    "burg.teil.fackel": "Fackel",
    "burg.teil.busch": "Busch",
    "burg.teil.fass": "Fass",
    "burg.ziel.tor": "🚪 Tor",
    "burg.ziel.wappen": "🛡️ Wappen",
    "burg.ziel.flagge": "🚩 Flagge",
    "burg.ziel.mauern": "🧱 6 Mauern",
    "burg.waehle": "Wähle ein Bauteil und tippe dann auf ein leeres Feld.",
    "burg.fehl": "Für {name} fehlen dir noch {n} Gold.",
    "burg.setzen": "Tippe ein leuchtendes Feld, um {name} zu setzen. Tippe auf ein gesetztes Teil, um es abzureißen.",
    "burg.passt.nicht": "{name} passt hier nicht hin.",
    "burg.pracht": "🏰 Prachtburg! Deine Burg ist vollständig – du kannst sie weiter ausbauen.",
    "burg.abgerissen": "{name} abgerissen – +{n} Gold zurück.",
    "burg.feld": "Feld {n}",
    "gekauft": "gekauft",

    "hoehle.stufe.ei": "Ei",
    "hoehle.stufe.schluepfling": "Schlüpfling",
    "hoehle.stufe.jungdrache": "Jungdrache",
    "hoehle.stufe.hausdrache": "Hausdrache",
    "hoehle.text.ei": "Ein warmes Ei liegt in der Höhle. Füttere es, damit es schlüpft.",
    "hoehle.text.schluepfling": "Geschlüpft! Ein winziger Drache blinzelt dich an.",
    "hoehle.text.jungdrache": "Er wächst – und fliegt ab jetzt im Drachenkampf an deiner Seite mit.",
    "hoehle.text.hausdrache": "Ausgewachsen! Dein Drache ist der Stolz der Höhle.",
    "hoehle.schmuck.nest": "Nest",
    "hoehle.schmuck.fackel": "Fackel",
    "hoehle.schmuck.gold": "Goldhaufen",
    "hoehle.schmuck.kristall": "Kristall",
    "hoehle.schmuck.knochen": "Knochen",
    "hoehle.schmuck.stern": "Sternenlicht",
    "hoehle.name.funkenschweif": "Funkenschweif",
    "hoehle.name.glutherz": "Glutherz",
    "hoehle.name.mondschuppe": "Mondschuppe",
    "hoehle.name.sternenzahn": "Sternenzahn",
    "hoehle.name.rauchwoelkchen": "Rauchwölkchen",
    "hoehle.name.goldkralle": "Goldkralle",
    "hoehle.ei.kaufen": "🥚 Drachenei kaufen – {n} Gold",
    "hoehle.still": "In der Höhle ist es still. Hier könnte dein eigener Drache wohnen.",
    "hoehle.brauchst.ei": "Du brauchst noch {n} Gold für das Ei.",
    "hoehle.genug.ei": "Du hast genug Gold – hol dir das Ei!",
    "hoehle.ausgewachsen": "🐉 Ausgewachsen!",
    "hoehle.fertig": "Dein Drache ist fertig gewachsen.",
    "hoehle.schmuecke": "Schmücke jetzt die Höhle – schöner wohnt er allemal.",
    "hoehle.fuettern": "🍖 Füttern – {n} Gold",
    "hoehle.noch": "noch {n}× füttern bis {name}",
    "hoehle.brauchst.futter": "Du brauchst noch {n} Gold fürs Futter.",
    "hoehle.hunger": "Dein Drache hat Hunger!",
    "hoehle.gewachsen": "🎉 Gewachsen! Jetzt ein {name}.",
    "hoehle.schmueckt": "{name} schmückt jetzt deine Höhle.",
    "hoehle.hinweis.start": "Verdiene Gold in den Rechenspielen und bring Leben in die Höhle.",
    "hoehle.name.titel": "Wie soll dein Drache hei\u00dfen?",
    "hoehle.name.text": "Tippe einen Namen an \u2013 er bleibt f\u00fcr immer.",
    "hoehle.hunger.mehr": { one: "Dein Drache braucht noch {n}\u00d7 Futter.", other: "Dein Drache braucht noch {n}\u00d7 Futter." },
    "hoehle.farben.titel": "Drachenfarbe",
    "farbe.feuer": "Feuerrot",
    "farbe.wald": "Waldgr\u00fcn",
    "farbe.eis": "Eisblau",
    "farbe.nacht": "Nachtviolett",
    "farbe.gold": "Goldgelb",
    "farbe.rosen": "Rosenrot",
    "farbe.gesperrt": "noch {n} T\u00fcrme",
    "hunger.banner.titel": "Dein Drache hat Hunger",
    "hunger.banner.text": "Ab in die H\u00f6hle und f\u00fcttern!",

    "m.frage": "Fülle die leuchtende Lücke der Mauer.",
    "m.rechne": "Rechne: {a} + {b}",
    "m.rechne.rueckwaerts": "Rechne rückwärts: {a} − {b}",
    "m.weiter": "Weiter mit der nächsten Lücke.",
    "m.falsch": "Richtig wäre: {loesung}",
    "m.falsch.gold": "Richtig wäre: {loesung}  −{n} Gold",
    "m.ziel.basis": { one: "{n} Lücke gefüllt, beste Serie: {b}.", other: "{n} Lücken gefüllt, beste Serie: {b}." },

    "t.gegner.blauhelm": "Ritter Blauhelm",
    "t.gegner.grauguss": "Graf Grauguss",
    "t.gegner.silberzahn": "Sir Silberzahn",
    "t.gegner.goldhelm": "König Goldhelm",
    "t.dein.ritter": "Dein Ritter",
    "t.ritt": "Ritt {n}/{m}",
    "t.aus.sattel": "{name} aus dem Sattel!",
    "t.weiter.gegen": "Du hast {n} Treffer gelandet – weiter geht's gegen {name}.",
    "t.staerker": "{name} war stärker",
    "t.verloren": "Du hast {n} gelöst, aber {m} Fehler gemacht. Noch ein Versuch?",
    "t.sieg": "Turnier gewonnen!",
    "t.sieg.text": "Alle Ritter sind besiegt – {n} gelöste Aufgaben, beste Serie: {b}.",
    "t.daneben": "Daneben! {loesung}",
    "t.daneben.gold": "Daneben! {loesung}  −{n} Gold.",

    "turm.frage.hoch": "Noch einmal so viel \u2013 eine Sprosse h\u00f6her!",
    "turm.frage.runter": "Zwei gleiche Sprossen ergeben die dar\u00fcber.",
    "turm.gipfel": "Oben! Da ist der Schatz.",
    "turm.unten.gold": "Goldene Truhe! Kein einziger Fehler.",
    "turm.unten.silber": "Silberne Truhe \u2013 geschafft!",
    "turm.abgerutscht": "Abgerutscht! Richtig w\u00e4re: {loesung}",
    "turm.abgerutscht.gold": "Abgerutscht! Richtig w\u00e4re: {loesung}  \u2212{n} Gold",
    "turm.halt": "Richtig w\u00e4re: {loesung} \u2013 du bleibst auf der Sprosse.",
    "turm.farbe.frei": "\ud83c\udfa8 Neue Drachenfarbe frei: {name}!",
    "turm.titel": "Alle T\u00fcrme erklommen!",
    "turm.weiter": "Weiter klettern",
    "turm.ziel.basis": { one: "{n} Sprosse geschafft, beste Serie: {b}.", other: "{n} Sprossen geschafft, beste Serie: {b}." },
    /* --- Uhrturm ------------------------------------------------------
       uhr.halb.bezug sagt, welche Stunde bei der halben Stunde genannt wird.
       Nur im Deutschen ist das die naechste: 3:30 ist "halb 4". Englisch,
       Spanisch, Franzoesisch und Tuerkisch nennen die aktuelle Stunde. */
    "uhr": "Runde",
    "uhr.halb.bezug": "naechste",
    "uhr.form.voll": "{n} Uhr",
    "uhr.form.halb": "halb {n}",
    "uhr.form.viertelnach": "viertel nach {n}",
    "uhr.form.viertelvor": "viertel vor {n}",
    "uhr.frage.ablesen": "Wie sp\u00e4t ist es?",
    "uhr.frage.zuordnen": "Welche Uhr zeigt das?",
    "uhr.tipp.voll": "Der kleine Zeiger sagt die Stunde, der gro\u00dfe steht auf der 12.",
    "uhr.tipp.halb": "Der gro\u00dfe Zeiger steht auf der 6. Der kleine ist schon fast bei der n\u00e4chsten Zahl.",
    "uhr.tipp.viertel": "Der gro\u00dfe Zeiger steht auf der 3 oder auf der 9 \u2013 eine Viertelstunde nach oder vor der vollen Stunde.",
    "uhr.glocke": "Die Glocke l\u00e4utet!",
    "uhr.falsch": "Es ist {zeit}.",
    "uhr.falsch.gold": "Es ist {zeit}.  \u2212{n} Gold",
    "uhr.bonus.knopf": "\ud83d\udd14 Bonus: Viertelstunden",
    "uhr.bonus.start": "Bonusrunde! Jetzt kommen die Viertelstunden.",
    "uhr.titel": "Die Turmuhr geht wieder!",
    "uhr.weiter": "Noch einmal",
    "uhr.ziel.basis": { one: "{n} Uhrzeit richtig gelesen, beste Serie: {b}.", other: "{n} Uhrzeiten richtig gelesen, beste Serie: {b}." },

    "truhe.titel": "Eine Schatztruhe!",
    "truhe.text": "Tippe die Truhe an.",
    "truhe.gefunden": "{name} gefunden!",
    "truhe.neu": "Neu in deiner Schatzkammer – {n} von {m}.",
    "truhe.gold.voll": "Randvoll mit Gold!",
    "truhe.alle": "Du hast schon alle Schätze – dafür klingelt die Kasse.",
    "truhe.weiter": "Weiter rechnen",

    "kammer.titel": "Deine Schatzkammer",
    "kammer.text": { one: "{n} von {m} Schatz gefunden", other: "{n} von {m} Schätzen gefunden" },
    "kammer.gesperrt": "🔒 Spiel weiter, um ihn zu finden!",
    "kammer.noch.offen": "noch offen",
    "kammer.neu": "NEU",
    "kammer.gold": "🪙 {n} Gold · {rang}",

    "konto.titel": "Wer spielt?",
    "konto.neu": "Neues Kind",
    "konto.neu.text": "Wähle ein Bild und schreibe deinen Namen (oder lass ihn frei).",
    "konto.name.placeholder": "Dein Name (optional)",
    "konto.fertig": "Fertig",
    "konto.abbrechen": "Abbrechen",
    "konto.default.name": "Ritter {n}",
    "sprache.titel": "Sprache",

    "win.weiter": "Nächster Drache",
    "ende.nochmal": "Noch einmal",
    "ende.richtig": "richtig",
    "ende.serie": "beste Serie",
    "ende.gold": "Gold verdient",

    "ziel.titel": "Tagesziel geschafft!",
    "ziel.weiter": "Weiter sammeln",
    "ziel.bonus": "+100 Bonus-Gold",
    "mauer.titel": "Alle Rechenmauern geschafft!",
    "mauer.weiter": "Weiter mauern",
    "turnier.weiter": "Weiter",

    "aria.antwort": "Antwort {n}",
    "aria.burgbaustelle": "Burgbaustelle",
    "aria.bauteile": "Bauteile",
    "aria.hoehle.schmuck": "Höhlenschmuck",
    "aria.mauer": "Rechenmauer",
    "aria.turm": "Drachenturm",
    "aria.uhr": "Turmuhr",
    "aria.uhr.wahl": "Uhr {n}",
    "aria.puzzlebild": "Puzzlebild",
    "aria.bild.geloest": "Gelöstes Puzzlebild"
  },

  en: {
    "title": "Math Knights – addition and subtraction up to 20",
    "start.titel": "Math Knights",
    "start.untertitel": "Math becomes an adventure",
    "wer.spielt": "Who's playing?",
    "konto.tippe": "Tap your picture.",
    "dein.rang": "Your rank",
    "frage.raum": "How far do we count?",
    "frage.art": "What do we practise?",
    "raum.bis10": "up to 10",
    "raum.bis20": "up to 20",
    "art.plus": "addition only",
    "art.beides": "addition and subtraction",
    "wahl.ausgewaehlt": "✓ selected",
    "konto.du.bist.dran": "✓ your turn",
    "spielen.verdienen": "🎯 Play & Earn",
    "gold.ausgeben": "🪙 Spend gold",
    "badge.verdienen": "Earn",
    "badge.ausgeben": "Spend",
    "badge.ansehen": "View",
    "ton.an": "🔊 Sound on",
    "ton.aus": "🔇 Sound off",
    "ton.kurz": "🔊 Sound",
    "heim": "🏠 Home",
    "kammer": "🗝️ Treasury",
    "tipp": "💡 Hint",
    "gold": "Gold",
    "serie": "Streak",
    "aufgabe": "Task",
    "puzzle": "Puzzle",
    "teile": "Pieces",
    "mauer": "Wall",
    "turm": "Tower",
    "gegner": "Foe",
    "futter": "Food",
    "drache": "Dragon",
    "burgwert": "Castle value",
    "bilder": "Pictures",
    "zurueck": "Back",

    "schatz.diamant": "Diamond",
    "schatz.krone": "Crown",
    "schatz.schluessel": "Golden key",
    "schatz.stab": "Magic wand",
    "schatz.schwert": "Flame sword",
    "schatz.schild": "Silver shield",
    "schatz.ei": "Dragon egg",
    "schatz.einhorn": "Unicorn",
    "schatz.kompass": "Compass",
    "schatz.laterne": "Eternal light",
    "schatz.vase": "Golden vase",
    "schatz.perle": "Rainbow pearl",
    "galerie.kurz": "🖼️ Gallery",
    "puzzle.kurz": "🧩 Puzzle",

    "karte.kampf.titel": "Knights vs Dragons",
    "karte.kampf.text": "Knock out the dragon's fangs. Every hit earns gold.",
    "karte.hort.titel": "Treasure hunt",
    "karte.hort.text": "Collect gold at your own pace – no hearts, no losing.",
    "karte.mauer.titel": "Number wall",
    "karte.mauer.text": "Fill the gaps in the number wall and earn gold.",
    "karte.turnier.titel": "Knight tournament",
    "karte.turnier.text": "Strike with your lance – solve your way to the rival.",
    "karte.turm.titel": "Dragon tower",
    "karte.turm.text": "Climb the ladder up to the treasure \u2013 and back down again.",
    "karte.uhr.titel": "Clock tower",
    "karte.uhr.text": "Read the tower clock so the bell rings again.",
    "karte.puzzle.titel": "Puzzle treasure",
    "karte.puzzle.text": "Buy puzzle pieces for 200 gold and reveal the picture bit by bit.",
    "karte.galerie.titel": "Gallery",
    "karte.galerie.text": "Look at all the pictures you have already solved.",
    "karte.burg.titel": "Build a castle",
    "karte.burg.text": "Spend gold and build your castle stone by stone.",
    "karte.hoehle.titel": "Dragon's cave",
    "karte.hoehle.text": "Buy a dragon egg and raise your own dragon.",

    "rang.knappe": "Squire",
    "rang.ritter": "Knight",
    "rang.schatzmeister": "Treasurer",
    "rang.drachenreiter": "Dragon rider",
    "rang.legende": "Legend",
    "rang.baron": "Baron",
    "rang.graf": "Count",
    "rang.herzog": "Duke",
    "rang.fuerst": "Prince",
    "rang.koenig": "King",
    "rang.kaiser": "Emperor",
    "rang.drachentoeter": "Dragonslayer",
    "rang.unsterblicher": "Immortal",
    "rang.gott.des.goldes": "God of Gold",
    "rang.fortschritt": "{n} more until {rang}",
    "rang.max": "Highest rank reached! 🌠",
    "rang.neu": "New rank!",

    "drache.glutzahn": "Embertooth",
    "drache.nebelschwinge": "Mistwing",
    "drache.frostkralle": "Frostclaw",
    "drache.schattenhorn": "Shadowhorn",
    "drache.koenigsdrache": "King Dragon",

    "k.partei.ritter": "Knight",
    "k.runde": "Dragon {n}/{m}",
    "frage.zahl": "Which number fits?",
    "k.falsch": "Correct would be: {loesung}",
    "k.falsch.gold": "Correct would be: {loesung}  −{n} gold",
    "k.win.titel": "{name} is defeated!",
    "k.win.beute": "🪙 +{n} gold dragon treasure",
    "k.win.text": "On to the next one: {name} is waiting. Your hearts are full again.",
    "k.ende.sieg.titel": "All dragons defeated!",
    "k.ende.sieg.text": "The kingdom is saved – and your dragon gold is in the treasury.",
    "k.ende.niederlage.titel": "The dragon was stronger",
    "k.ende.niederlage.text": "Your hearts are used up. Your gold stays with you – one more try?",

    "lob.treffer": "Hit!",
    "lob.stark": "Strong!",
    "lob.volltreffer": "Bullseye!",
    "lob.genau": "Exactly right!",
    "lob.perfekt": "Perfect!",
    "lob.super": "Great maths!",

    "gold.plus": "+{n} gold",

    "h.fast": "Almost! {loesung} – try again.",
    "h.fast.gold": "Almost! {loesung}  −{n} gold. Try again.",
    "h.serie": "🔥 Streak! From now ×{n} gold",
    "h.ziel.basis": { one: "{n} task done, best streak: {b}.", other: "{n} tasks done, best streak: {b}." },
    "h.ziel.sauber": "And not a single mistake!",
    "h.weiterso": "Keep it up!",

    "puzzle.kaufen": "🧩 Buy puzzle piece – {n} gold",
    "puzzle.eins": "🧩 1 puzzle piece",
    "puzzle.rest": { one: "{n} piece missing. Each purchase reveals a bit more.", other: "{n} pieces missing. Each purchase reveals a bit more." },
    "puzzle.brauchst": "You still need {n} gold.",
    "puzzle.genug": "You have enough gold – which piece will be visible next?",
    "puzzle.alle.btn": "🏆 All pictures collected!",
    "puzzle.alle.text": "Well done! You have fully revealed every picture.",
    "puzzle.alle.hinweis": "You can look at them all in the gallery.",
    "puzzle.geloest.btn": "🏆 Puzzle solved!",
    "puzzle.geloest.text": "Well done! The picture is fully revealed.",
    "puzzle.geloest.hinweis": "The next puzzle is being prepared …",
    "puzzle.funken": "🎉 Puzzle solved!",
    "puzzle.wandert": "It moves into the gallery – the next adventure awaits!",
    "puzzle.alle.galerie": "All pictures are now hanging in your gallery!",

    "galerie.titel": "🖼️ Your gallery",
    "galerie.leer": "No picture finished yet – solve a puzzle and it will hang here.",
    "galerie.alle": "All {n} pictures collected! Tap one.",
    "galerie.teile": { one: "{n} of {m} picture finished. Tap it.", other: "{n} of {m} pictures finished. Tap one." },
    "galerie.teile.kurz": "{n}/{m} pieces",
    "galerie.noch.zu": "locked",
    "bild.titel": "Picture {n}",
    "bild.hinweis": "Tap the picture to see it bigger.",
    "bild.zoom": "Slide your finger over the picture. Tap again to make it small.",

    "burg.teil.mauer": "Wall",
    "burg.teil.rote-mauer": "Brick",
    "burg.teil.turmstein": "Tower stone",
    "burg.teil.tor": "Gate",
    "burg.teil.fenster": "Window",
    "burg.teil.dach": "Roof",
    "burg.teil.flagge": "Flag",
    "burg.teil.wappen": "Coat of arms",
    "burg.teil.fackel": "Torch",
    "burg.teil.busch": "Bush",
    "burg.teil.fass": "Barrel",
    "burg.ziel.tor": "🚪 Gate",
    "burg.ziel.wappen": "🛡️ Coat of arms",
    "burg.ziel.flagge": "🚩 Flag",
    "burg.ziel.mauern": "🧱 6 walls",
    "burg.waehle": "Choose a part and then tap an empty square.",
    "burg.fehl": "You need {n} more gold for {name}.",
    "burg.setzen": "Tap a glowing square to place {name}. Tap a placed part to tear it down.",
    "burg.passt.nicht": "{name} doesn't fit here.",
    "burg.pracht": "🏰 Splendid castle! It is complete – you can keep building.",
    "burg.abgerissen": "{name} torn down – +{n} gold back.",
    "burg.feld": "Square {n}",
    "gekauft": "bought",

    "hoehle.stufe.ei": "Egg",
    "hoehle.stufe.schluepfling": "Hatchling",
    "hoehle.stufe.jungdrache": "Young dragon",
    "hoehle.stufe.hausdrache": "House dragon",
    "hoehle.text.ei": "A warm egg lies in the cave. Feed it so it hatches.",
    "hoehle.text.schluepfling": "It hatched! A tiny dragon blinks at you.",
    "hoehle.text.jungdrache": "It grows – and now flies at your side in dragon battles.",
    "hoehle.text.hausdrache": "Fully grown! Your dragon is the pride of the cave.",
    "hoehle.schmuck.nest": "Nest",
    "hoehle.schmuck.fackel": "Torch",
    "hoehle.schmuck.gold": "Pile of gold",
    "hoehle.schmuck.kristall": "Crystal",
    "hoehle.schmuck.knochen": "Bone",
    "hoehle.schmuck.stern": "Starlight",
    "hoehle.name.funkenschweif": "Sparkswirl",
    "hoehle.name.glutherz": "Emberheart",
    "hoehle.name.mondschuppe": "Moonscale",
    "hoehle.name.sternenzahn": "Startooth",
    "hoehle.name.rauchwoelkchen": "Smokepuff",
    "hoehle.name.goldkralle": "Goldclaw",
    "hoehle.ei.kaufen": "🥚 Buy dragon egg – {n} gold",
    "hoehle.still": "The cave is quiet. Your own dragon could live here.",
    "hoehle.brauchst.ei": "You still need {n} gold for the egg.",
    "hoehle.genug.ei": "You have enough gold – go get the egg!",
    "hoehle.ausgewachsen": "🐉 Fully grown!",
    "hoehle.fertig": "Your dragon has finished growing.",
    "hoehle.schmuecke": "Now decorate the cave – it will like it there.",
    "hoehle.fuettern": "🍖 Feed – {n} gold",
    "hoehle.noch": "{n}× more feeds until {name}",
    "hoehle.brauchst.futter": "You still need {n} gold for food.",
    "hoehle.hunger": "Your dragon is hungry!",
    "hoehle.gewachsen": "🎉 Grown! Now a {name}.",
    "hoehle.schmueckt": "{name} now decorates your cave.",
    "hoehle.hinweis.start": "Earn gold in the maths games and bring the cave to life.",
    "hoehle.name.titel": "What should your dragon be called?",
    "hoehle.name.text": "Tap a name \u2013 it stays forever.",
    "hoehle.hunger.mehr": { one: "Your dragon needs {n} more meal.", other: "Your dragon needs {n} more meals." },
    "hoehle.farben.titel": "Dragon colour",
    "farbe.feuer": "Fire red",
    "farbe.wald": "Forest green",
    "farbe.eis": "Ice blue",
    "farbe.nacht": "Night purple",
    "farbe.gold": "Golden yellow",
    "farbe.rosen": "Rose pink",
    "farbe.gesperrt": "{n} more towers",
    "hunger.banner.titel": "Your dragon is hungry",
    "hunger.banner.text": "Off to the cave and feed it!",

    "m.frage": "Fill the glowing gap in the wall.",
    "m.rechne": "Calculate: {a} + {b}",
    "m.rechne.rueckwaerts": "Work backwards: {a} − {b}",
    "m.weiter": "On to the next gap.",
    "m.falsch": "Correct would be: {loesung}",
    "m.falsch.gold": "Correct would be: {loesung}  −{n} gold",
    "m.ziel.basis": { one: "{n} gap filled, best streak: {b}.", other: "{n} gaps filled, best streak: {b}." },

    "t.gegner.blauhelm": "Knight Bluehelm",
    "t.gegner.grauguss": "Count Greysteel",
    "t.gegner.silberzahn": "Sir Silvertooth",
    "t.gegner.goldhelm": "King Goldhelm",
    "t.dein.ritter": "Your knight",
    "t.ritt": "Ride {n}/{m}",
    "t.aus.sattel": "{name} is unhorsed!",
    "t.weiter.gegen": "You scored {n} hits – on to {name}.",
    "t.staerker": "{name} was stronger",
    "t.verloren": "You solved {n}, but made {m} mistakes. Another try?",
    "t.sieg": "Tournament won!",
    "t.sieg.text": "All knights are defeated – {n} tasks solved, best streak: {b}.",
    "t.daneben": "Missed! {loesung}",
    "t.daneben.gold": "Missed! {loesung}  −{n} gold.",

    "turm.frage.hoch": "Just as much again \u2013 one rung higher!",
    "turm.frage.runter": "Two equal rungs make the one above.",
    "turm.gipfel": "At the top! There is the treasure.",
    "turm.unten.gold": "Golden chest! Not a single mistake.",
    "turm.unten.silber": "Silver chest \u2013 you made it!",
    "turm.abgerutscht": "You slipped! The answer was: {loesung}",
    "turm.abgerutscht.gold": "You slipped! The answer was: {loesung}  \u2212{n} gold",
    "turm.halt": "The answer was: {loesung} \u2013 you stay on this rung.",
    "turm.farbe.frei": "\ud83c\udfa8 New dragon colour unlocked: {name}!",
    "turm.titel": "All towers climbed!",
    "turm.weiter": "Keep climbing",
    "turm.ziel.basis": { one: "{n} rung done, best streak: {b}.", other: "{n} rungs done, best streak: {b}." },
    /* --- Clock tower --- */
    "uhr": "Round",
    "uhr.halb.bezug": "aktuelle",
    "uhr.form.voll": "{n} o\u2019clock",
    "uhr.form.halb": "half past {n}",
    "uhr.form.viertelnach": "quarter past {n}",
    "uhr.form.viertelvor": "quarter to {n}",
    "uhr.frage.ablesen": "What time is it?",
    "uhr.frage.zuordnen": "Which clock shows this?",
    "uhr.tipp.voll": "The small hand tells the hour, the big one points at 12.",
    "uhr.tipp.halb": "The big hand points at 6, halfway round the clock.",
    "uhr.tipp.viertel": "The big hand points at 3 or at 9 \u2013 a quarter of an hour past or to the full hour.",
    "uhr.glocke": "The bell rings!",
    "uhr.falsch": "It is {zeit}.",
    "uhr.falsch.gold": "It is {zeit}.  \u2212{n} gold",
    "uhr.bonus.knopf": "\ud83d\udd14 Bonus: quarter hours",
    "uhr.bonus.start": "Bonus round! Now the quarter hours.",
    "uhr.titel": "The tower clock runs again!",
    "uhr.weiter": "Once more",
    "uhr.ziel.basis": { one: "{n} time read correctly, best streak: {b}.", other: "{n} times read correctly, best streak: {b}." },

    "truhe.titel": "A treasure chest!",
    "truhe.text": "Tap the chest.",
    "truhe.gefunden": "{name} found!",
    "truhe.neu": "New in your treasury – {n} of {m}.",
    "truhe.gold.voll": "Full of gold!",
    "truhe.alle": "You already have all treasures – so the till rings.",
    "truhe.weiter": "Keep calculating",

    "kammer.titel": "Your treasury",
    "kammer.text": { one: "{n} of {m} treasure found", other: "{n} of {m} treasures found" },
    "kammer.gesperrt": "🔒 Keep playing to find it!",
    "kammer.noch.offen": "still locked",
    "kammer.neu": "NEW",
    "kammer.gold": "🪙 {n} gold · {rang}",

    "konto.titel": "Who's playing?",
    "konto.neu": "New child",
    "konto.neu.text": "Choose a picture and write your name (or leave it blank).",
    "konto.name.placeholder": "Your name (optional)",
    "konto.fertig": "Done",
    "konto.abbrechen": "Cancel",
    "konto.default.name": "Knight {n}",
    "sprache.titel": "Language",

    "win.weiter": "Next dragon",
    "ende.nochmal": "Once more",
    "ende.richtig": "correct",
    "ende.serie": "best streak",
    "ende.gold": "gold earned",

    "ziel.titel": "Daily goal reached!",
    "ziel.weiter": "Keep collecting",
    "ziel.bonus": "+100 bonus gold",
    "mauer.titel": "All number walls done!",
    "mauer.weiter": "Keep walling",
    "turnier.weiter": "Continue",

    "aria.antwort": "Answer {n}",
    "aria.burgbaustelle": "Castle site",
    "aria.bauteile": "Parts",
    "aria.hoehle.schmuck": "Cave decorations",
    "aria.mauer": "Number wall",
    "aria.turm": "Dragon tower",
    "aria.uhr": "Tower clock",
    "aria.uhr.wahl": "Clock {n}",
    "aria.puzzlebild": "Puzzle picture",
    "aria.bild.geloest": "Solved puzzle picture"
  },

  es: {
    "title": "Caballeros de las mates – sumas y restas hasta 20",
    "start.titel": "Caballeros de las mates",
    "start.untertitel": "Las mates se convierten en una aventura",
    "wer.spielt": "¿Quién juega?",
    "konto.tippe": "Toca tu dibujo.",
    "dein.rang": "Tu rango",
    "frage.raum": "¿Hasta dónde contamos?",
    "frage.art": "¿Qué practicamos?",
    "raum.bis10": "hasta 10",
    "raum.bis20": "hasta 20",
    "art.plus": "solo sumas",
    "art.beides": "sumas y restas",
    "wahl.ausgewaehlt": "✓ elegido",
    "konto.du.bist.dran": "✓ te toca",
    "spielen.verdienen": "🎯 Jugar y ganar",
    "gold.ausgeben": "🪙 Gastar oro",
    "badge.verdienen": "Ganar",
    "badge.ausgeben": "Gastar",
    "badge.ansehen": "Ver",
    "ton.an": "🔊 Sonido activado",
    "ton.aus": "🔇 Sonido apagado",
    "ton.kurz": "🔊 Sonido",
    "heim": "🏠 Inicio",
    "kammer": "🗝️ Tesorería",
    "tipp": "💡 Pista",
    "gold": "Oro",
    "serie": "Racha",
    "aufgabe": "Tarea",
    "puzzle": "Puzle",
    "teile": "Piezas",
    "mauer": "Muro",
    "turm": "Torre",
    "gegner": "Rival",
    "futter": "Comida",
    "drache": "Dragón",
    "burgwert": "Valor del castillo",
    "bilder": "Imágenes",
    "zurueck": "Volver",

    "schatz.diamant": "Diamante",
    "schatz.krone": "Corona",
    "schatz.schluessel": "Llave de oro",
    "schatz.stab": "Varita mágica",
    "schatz.schwert": "Espada de fuego",
    "schatz.schild": "Escudo de plata",
    "schatz.ei": "Huevo de dragón",
    "schatz.einhorn": "Unicornio",
    "schatz.kompass": "Brújula",
    "schatz.laterne": "Luz eterna",
    "schatz.vase": "Jarrón de oro",
    "schatz.perle": "Perla arcoíris",
    "galerie.kurz": "🖼️ Galería",
    "puzzle.kurz": "🧩 Puzle",

    "karte.kampf.titel": "Caballeros contra dragones",
    "karte.kampf.text": "Arranca los colmillos al dragón. Cada acierto da oro.",
    "karte.hort.titel": "Caza del tesoro",
    "karte.hort.text": "Recoge oro tranquilo – sin corazones, sin perder.",
    "karte.mauer.titel": "Muro de números",
    "karte.mauer.text": "Rellena los huecos del muro y gana oro.",
    "karte.turnier.titel": "Torneo de caballeros",
    "karte.turnier.text": "Ataca con tu lanza y resuelve hasta llegar al rival.",
    "karte.turm.titel": "Torre del drag\u00f3n",
    "karte.turm.text": "Sube la escalera hasta el tesoro y vuelve a bajar.",
    "karte.uhr.titel": "Torre del reloj",
    "karte.uhr.text": "Lee el reloj de la torre para que vuelva a sonar la campana.",
    "karte.puzzle.titel": "Tesoro de puzle",
    "karte.puzzle.text": "Compra piezas por 200 de oro y revela el dibujo poco a poco.",
    "karte.galerie.titel": "Galería",
    "karte.galerie.text": "Mira todos los dibujos que ya has resuelto.",
    "karte.burg.titel": "Construir castillo",
    "karte.burg.text": "Gasta oro y levanta tu castillo piedra a piedra.",
    "karte.hoehle.titel": "Cueva del dragón",
    "karte.hoehle.text": "Compra un huevo de dragón y cría tu propio dragón.",

    "rang.knappe": "Escudero",
    "rang.ritter": "Caballero",
    "rang.schatzmeister": "Tesorero",
    "rang.drachenreiter": "Jinete de dragón",
    "rang.legende": "Leyenda",
    "rang.baron": "Barón",
    "rang.graf": "Conde",
    "rang.herzog": "Duque",
    "rang.fuerst": "Príncipe",
    "rang.koenig": "Rey",
    "rang.kaiser": "Emperador",
    "rang.drachentoeter": "Matadragones",
    "rang.unsterblicher": "Inmortal",
    "rang.gott.des.goldes": "Dios del Oro",
    "rang.fortschritt": "{n} más hasta {rang}",
    "rang.max": "¡Rango máximo alcanzado! 🌠",
    "rang.neu": "¡Nuevo rango!",

    "drache.glutzahn": "Dientebrasa",
    "drache.nebelschwinge": "Alaneblina",
    "drache.frostkralle": "Garrahelada",
    "drache.schattenhorn": "Cuernosombra",
    "drache.koenigsdrache": "Dragón Rey",

    "k.partei.ritter": "Caballero",
    "k.runde": "Dragón {n}/{m}",
    "frage.zahl": "¿Qué número encaja?",
    "k.falsch": "Lo correcto sería: {loesung}",
    "k.falsch.gold": "Lo correcto sería: {loesung}  −{n} de oro",
    "k.win.titel": "¡{name} está vencido!",
    "k.win.beute": "🪙 +{n} de oro, tesoro del dragón",
    "k.win.text": "Seguimos: {name} ya espera. Tienes todos los corazones otra vez.",
    "k.ende.sieg.titel": "¡Todos los dragones vencidos!",
    "k.ende.sieg.text": "El reino está salvado – y tu oro está en la tesorería.",
    "k.ende.niederlage.titel": "El dragón fue más fuerte",
    "k.ende.niederlage.text": "Te quedaste sin corazones. Tu oro sigue contigo – ¿otro intento?",

    "lob.treffer": "¡Acierto!",
    "lob.stark": "¡Fuerte!",
    "lob.volltreffer": "¡En el blanco!",
    "lob.genau": "¡Exacto!",
    "lob.perfekt": "¡Perfecto!",
    "lob.super": "¡Mates geniales!",

    "gold.plus": "+{n} de oro",

    "h.fast": "¡Casi! {loesung} – otra vez.",
    "h.fast.gold": "¡Casi! {loesung}  −{n} de oro. Otra vez.",
    "h.serie": "🔥 ¡Racha! A partir de ahora ×{n} de oro",
    "h.ziel.basis": { one: "{n} tarea hecha, mejor racha: {b}.", other: "{n} tareas hechas, mejor racha: {b}." },
    "h.ziel.sauber": "¡Y ni un solo error!",
    "h.weiterso": "¡Sigue así!",

    "puzzle.kaufen": "🧩 Comprar pieza – {n} de oro",
    "puzzle.eins": "🧩 1 pieza de puzle",
    "puzzle.rest": { one: "Falta {n} pieza. Cada compra revela un poco más.", other: "Faltan {n} piezas. Cada compra revela un poco más." },
    "puzzle.brauchst": "Todavía necesitas {n} de oro.",
    "puzzle.genug": "Tienes oro suficiente – ¿qué pieza se verá ahora?",
    "puzzle.alle.btn": "🏆 ¡Todas las imágenes conseguidas!",
    "puzzle.alle.text": "¡Logrado! Has revelado todas las imágenes.",
    "puzzle.alle.hinweis": "Puedes verlas todas en la galería.",
    "puzzle.geloest.btn": "🏆 ¡Puzle resuelto!",
    "puzzle.geloest.text": "¡Logrado! La imagen está completa.",
    "puzzle.geloest.hinweis": "Se prepara el siguiente puzle …",
    "puzzle.funken": "🎉 ¡Puzle resuelto!",
    "puzzle.wandert": "Va a la galería – ¡la próxima aventura espera!",
    "puzzle.alle.galerie": "¡Todas las imágenes están ya en tu galería!",

    "galerie.titel": "🖼️ Tu galería",
    "galerie.leer": "Aún no hay ninguna imagen – resuelve un puzle y aparecerá aquí.",
    "galerie.alle": "¡Las {n} imágenes conseguidas! Toca una.",
    "galerie.teile": { one: "{n} de {m} imagen terminada. Tócala.", other: "{n} de {m} imágenes terminadas. Toca una." },
    "galerie.teile.kurz": "{n}/{m} piezas",
    "galerie.noch.zu": "cerrado",
    "bild.titel": "Imagen {n}",
    "bild.hinweis": "Toca la imagen para verla más grande.",
    "bild.zoom": "Desliza el dedo por la imagen. Toca otra vez para hacerla pequeña.",

    "burg.teil.mauer": "Muro",
    "burg.teil.rote-mauer": "Ladrillo",
    "burg.teil.turmstein": "Piedra de torre",
    "burg.teil.tor": "Puerta",
    "burg.teil.fenster": "Ventana",
    "burg.teil.dach": "Tejado",
    "burg.teil.flagge": "Bandera",
    "burg.teil.wappen": "Escudo",
    "burg.teil.fackel": "Antorcha",
    "burg.teil.busch": "Arbusto",
    "burg.teil.fass": "Barril",
    "burg.ziel.tor": "🚪 Puerta",
    "burg.ziel.wappen": "🛡️ Escudo",
    "burg.ziel.flagge": "🚩 Bandera",
    "burg.ziel.mauern": "🧱 6 muros",
    "burg.waehle": "Elige una pieza y toca una casilla vacía.",
    "burg.fehl": "Necesitas {n} de oro más para {name}.",
    "burg.setzen": "Toca una casilla brillante para poner {name}. Toca una pieza puesta para derribarla.",
    "burg.passt.nicht": "{name} no cabe aquí.",
    "burg.pracht": "🏰 ¡Castillo espléndido! Está completo – puedes seguir ampliándolo.",
    "burg.abgerissen": "{name} derribado – +{n} de oro de vuelta.",
    "burg.feld": "Casilla {n}",
    "gekauft": "comprado",

    "hoehle.stufe.ei": "Huevo",
    "hoehle.stufe.schluepfling": "Cría",
    "hoehle.stufe.jungdrache": "Dragón joven",
    "hoehle.stufe.hausdrache": "Dragón casero",
    "hoehle.text.ei": "Un huevo caliente está en la cueva. Dale de comer para que eclosione.",
    "hoehle.text.schluepfling": "¡Ha eclosionado! Un dragón diminuto te mira parpadeando.",
    "hoehle.text.jungdrache": "Crece – y ahora vuela contigo en los combates de dragones.",
    "hoehle.text.hausdrache": "¡Adulto! Tu dragón es el orgullo de la cueva.",
    "hoehle.schmuck.nest": "Nido",
    "hoehle.schmuck.fackel": "Antorcha",
    "hoehle.schmuck.gold": "Montón de oro",
    "hoehle.schmuck.kristall": "Cristal",
    "hoehle.schmuck.knochen": "Hueso",
    "hoehle.schmuck.stern": "Luz de estrellas",
    "hoehle.name.funkenschweif": "Colachispa",
    "hoehle.name.glutherz": "Corazón de brasa",
    "hoehle.name.mondschuppe": "Escamaluna",
    "hoehle.name.sternenzahn": "Dienteestelar",
    "hoehle.name.rauchwoelkchen": "Humito",
    "hoehle.name.goldkralle": "Garra de oro",
    "hoehle.ei.kaufen": "🥚 Comprar huevo de dragón – {n} de oro",
    "hoehle.still": "La cueva está en silencio. Aquí podría vivir tu propio dragón.",
    "hoehle.brauchst.ei": "Todavía necesitas {n} de oro para el huevo.",
    "hoehle.genug.ei": "Tienes oro suficiente – ¡ve a por el huevo!",
    "hoehle.ausgewachsen": "🐉 ¡Adulto!",
    "hoehle.fertig": "Tu dragón ha terminado de crecer.",
    "hoehle.schmuecke": "Ahora decora la cueva – allí estará a gusto.",
    "hoehle.fuettern": "🍖 Dar de comer – {n} de oro",
    "hoehle.noch": "{n}× comidas más hasta {name}",
    "hoehle.brauchst.futter": "Todavía necesitas {n} de oro para la comida.",
    "hoehle.hunger": "¡Tu dragón tiene hambre!",
    "hoehle.gewachsen": "🎉 ¡Ha crecido! Ahora es un {name}.",
    "hoehle.schmueckt": "{name} decora ahora tu cueva.",
    "hoehle.hinweis.start": "Gana oro en los juegos de mates y da vida a la cueva.",
    "hoehle.name.titel": "\u00bfC\u00f3mo se va a llamar tu drag\u00f3n?",
    "hoehle.name.text": "Toca un nombre: se queda para siempre.",
    "hoehle.hunger.mehr": { one: "Tu drag\u00f3n necesita {n} comida m\u00e1s.", other: "Tu drag\u00f3n necesita {n} comidas m\u00e1s." },
    "hoehle.farben.titel": "Color del drag\u00f3n",
    "farbe.feuer": "Rojo fuego",
    "farbe.wald": "Verde bosque",
    "farbe.eis": "Azul hielo",
    "farbe.nacht": "Violeta noche",
    "farbe.gold": "Amarillo oro",
    "farbe.rosen": "Rosa",
    "farbe.gesperrt": "faltan {n} torres",
    "hunger.banner.titel": "Tu drag\u00f3n tiene hambre",
    "hunger.banner.text": "\u00a1A la cueva a darle de comer!",

    "m.frage": "Rellena el hueco brillante del muro.",
    "m.rechne": "Calcula: {a} + {b}",
    "m.rechne.rueckwaerts": "Hacia atrás: {a} − {b}",
    "m.weiter": "Vamos al siguiente hueco.",
    "m.falsch": "Lo correcto sería: {loesung}",
    "m.falsch.gold": "Lo correcto sería: {loesung}  −{n} de oro",
    "m.ziel.basis": { one: "{n} hueco rellenado, mejor racha: {b}.", other: "{n} huecos rellenados, mejor racha: {b}." },

    "t.gegner.blauhelm": "Caballero Yelmoazul",
    "t.gegner.grauguss": "Conde Grisacero",
    "t.gegner.silberzahn": "Sir Dienteplata",
    "t.gegner.goldhelm": "Rey Yelmodeoro",
    "t.dein.ritter": "Tu caballero",
    "t.ritt": "Carga {n}/{m}",
    "t.aus.sattel": "¡{name} cae de la silla!",
    "t.weiter.gegen": "Has dado {n} golpes – seguimos contra {name}.",
    "t.staerker": "{name} fue más fuerte",
    "t.verloren": "Resolviste {n}, pero cometiste {m} errores. ¿Otro intento?",
    "t.sieg": "¡Torneo ganado!",
    "t.sieg.text": "Todos los caballeros vencidos – {n} tareas resueltas, mejor racha: {b}.",
    "t.daneben": "¡Fallaste! {loesung}",
    "t.daneben.gold": "¡Fallaste! {loesung}  −{n} de oro.",

    "turm.frage.hoch": "\u00a1Otra vez lo mismo: un pelda\u00f1o m\u00e1s arriba!",
    "turm.frage.runter": "Dos pelda\u00f1os iguales forman el de arriba.",
    "turm.gipfel": "\u00a1Arriba! Ah\u00ed est\u00e1 el tesoro.",
    "turm.unten.gold": "\u00a1Cofre dorado! Ni un solo fallo.",
    "turm.unten.silber": "Cofre de plata: \u00a1lo lograste!",
    "turm.abgerutscht": "\u00a1Te resbalaste! Era: {loesung}",
    "turm.abgerutscht.gold": "\u00a1Te resbalaste! Era: {loesung}  \u2212{n} oro",
    "turm.halt": "Era: {loesung}. Te quedas en el pelda\u00f1o.",
    "turm.farbe.frei": "\ud83c\udfa8 \u00a1Nuevo color de drag\u00f3n desbloqueado: {name}!",
    "turm.titel": "\u00a1Todas las torres escaladas!",
    "turm.weiter": "Seguir subiendo",
    "turm.ziel.basis": { one: "{n} pelda\u00f1o logrado, mejor racha: {b}.", other: "{n} pelda\u00f1os logrados, mejor racha: {b}." },
    /* --- Torre del reloj --- */
    "uhr": "Ronda",
    "uhr.halb.bezug": "aktuelle",
    "uhr.form.voll": "{n} en punto",
    "uhr.form.halb": "{n} y media",
    "uhr.form.viertelnach": "{n} y cuarto",
    "uhr.form.viertelvor": "{n} menos cuarto",
    "uhr.frage.ablesen": "\u00bfQu\u00e9 hora es?",
    "uhr.frage.zuordnen": "\u00bfQu\u00e9 reloj lo muestra?",
    "uhr.tipp.voll": "La aguja peque\u00f1a dice la hora, la grande se\u00f1ala el 12.",
    "uhr.tipp.halb": "La aguja grande se\u00f1ala el 6, media vuelta del reloj.",
    "uhr.tipp.viertel": "La aguja grande se\u00f1ala el 3 o el 9 \u2013 un cuarto de hora despu\u00e9s o antes.",
    "uhr.glocke": "\u00a1Suena la campana!",
    "uhr.falsch": "Son las {zeit}.",
    "uhr.falsch.gold": "Son las {zeit}.  \u2212{n} de oro",
    "uhr.bonus.knopf": "\ud83d\udd14 Bonus: los cuartos",
    "uhr.bonus.start": "\u00a1Ronda de bonus! Ahora los cuartos de hora.",
    "uhr.titel": "\u00a1El reloj de la torre funciona!",
    "uhr.weiter": "Otra vez",
    "uhr.ziel.basis": { one: "{n} hora le\u00edda bien, mejor racha: {b}.", other: "{n} horas le\u00eddas bien, mejor racha: {b}." },

    "truhe.titel": "¡Un cofre del tesoro!",
    "truhe.text": "Toca el cofre.",
    "truhe.gefunden": "¡{name} encontrado!",
    "truhe.neu": "Nuevo en tu tesorería – {n} de {m}.",
    "truhe.gold.voll": "¡Lleno de oro!",
    "truhe.alle": "Ya tienes todos los tesoros – por eso suena la caja.",
    "truhe.weiter": "Seguir calculando",

    "kammer.titel": "Tu tesorería",
    "kammer.text": { one: "{n} de {m} tesoro encontrado", other: "{n} de {m} tesoros encontrados" },
    "kammer.gesperrt": "🔒 ¡Sigue jugando para encontrarlo!",
    "kammer.noch.offen": "cerrado",
    "kammer.neu": "NUEVO",
    "kammer.gold": "🪙 {n} de oro · {rang}",

    "konto.titel": "¿Quién juega?",
    "konto.neu": "Niño nuevo",
    "konto.neu.text": "Elige un dibujo y escribe tu nombre (o déjalo en blanco).",
    "konto.name.placeholder": "Tu nombre (opcional)",
    "konto.fertig": "Listo",
    "konto.abbrechen": "Cancelar",
    "konto.default.name": "Caballero {n}",
    "sprache.titel": "Idioma",

    "win.weiter": "Siguiente dragón",
    "ende.nochmal": "Otra vez",
    "ende.richtig": "correcto",
    "ende.serie": "mejor racha",
    "ende.gold": "oro ganado",

    "ziel.titel": "¡Objetivo diario logrado!",
    "ziel.weiter": "Seguir coleccionando",
    "ziel.bonus": "+100 de oro extra",
    "mauer.titel": "¡Todos los muros de números hechos!",
    "mauer.weiter": "Seguir con los muros",
    "turnier.weiter": "Continuar",

    "aria.antwort": "Respuesta {n}",
    "aria.burgbaustelle": "Obra del castillo",
    "aria.bauteile": "Piezas",
    "aria.hoehle.schmuck": "Decoración de la cueva",
    "aria.mauer": "Muro de números",
    "aria.turm": "Torre del drag\u00f3n",
    "aria.uhr": "Reloj de la torre",
    "aria.uhr.wahl": "Reloj {n}",
    "aria.puzzlebild": "Imagen del puzle",
    "aria.bild.geloest": "Imagen de puzle resuelta"
  },

  fr: {
    "title": "Chevaliers des maths – additions et soustractions jusqu'à 20",
    "start.titel": "Chevaliers des maths",
    "start.untertitel": "Les maths deviennent une aventure",
    "wer.spielt": "Qui joue ?",
    "konto.tippe": "Touche ton image.",
    "dein.rang": "Ton rang",
    "frage.raum": "Jusqu'où comptons-nous ?",
    "frage.art": "Qu'entraînons-nous ?",
    "raum.bis10": "jusqu'à 10",
    "raum.bis20": "jusqu'à 20",
    "art.plus": "additions seulement",
    "art.beides": "additions et soustractions",
    "wahl.ausgewaehlt": "✓ choisi",
    "konto.du.bist.dran": "✓ à toi",
    "spielen.verdienen": "🎯 Jouer & gagner",
    "gold.ausgeben": "🪙 Dépenser de l'or",
    "badge.verdienen": "Gagner",
    "badge.ausgeben": "Dépenser",
    "badge.ansehen": "Voir",
    "ton.an": "🔊 Son activé",
    "ton.aus": "🔇 Son coupé",
    "ton.kurz": "🔊 Son",
    "heim": "🏠 Accueil",
    "kammer": "🗝️ Trésor",
    "tipp": "💡 Indice",
    "gold": "Or",
    "serie": "Série",
    "aufgabe": "Exercice",
    "puzzle": "Puzzle",
    "teile": "Pièces",
    "mauer": "Mur",
    "turm": "Tour",
    "gegner": "Adversaire",
    "futter": "Nourriture",
    "drache": "Dragon",
    "burgwert": "Valeur du château",
    "bilder": "Images",
    "zurueck": "Retour",

    "schatz.diamant": "Diamant",
    "schatz.krone": "Couronne",
    "schatz.schluessel": "Clé d'or",
    "schatz.stab": "Baguette magique",
    "schatz.schwert": "Épée de feu",
    "schatz.schild": "Bouclier d'argent",
    "schatz.ei": "Œuf de dragon",
    "schatz.einhorn": "Licorne",
    "schatz.kompass": "Boussole",
    "schatz.laterne": "Lumière éternelle",
    "schatz.vase": "Vase d'or",
    "schatz.perle": "Perle arc-en-ciel",
    "galerie.kurz": "🖼️ Galerie",
    "puzzle.kurz": "🧩 Puzzle",

    "karte.kampf.titel": "Chevaliers contre dragons",
    "karte.kampf.text": "Arrache les crocs au dragon. Chaque réussite rapporte de l'or.",
    "karte.hort.titel": "Chasse au trésor",
    "karte.hort.text": "Récolte de l'or tranquillement – sans cœurs, sans perdre.",
    "karte.mauer.titel": "Mur de nombres",
    "karte.mauer.text": "Comble les trous du mur et gagne de l'or.",
    "karte.turnier.titel": "Tournoi de chevaliers",
    "karte.turnier.text": "Frappe avec ta lance et calcule jusqu'à l'adversaire.",
    "karte.turm.titel": "Tour du dragon",
    "karte.turm.text": "Grimpe \u00e0 l'\u00e9chelle jusqu'au tr\u00e9sor \u2013 puis redescends.",
    "karte.uhr.titel": "Tour de l'horloge",
    "karte.uhr.text": "Lis l'horloge de la tour pour que la cloche sonne de nouveau.",
    "karte.puzzle.titel": "Trésor puzzle",
    "karte.puzzle.text": "Achète des pièces pour 200 d'or et révèle l'image petit à petit.",
    "karte.galerie.titel": "Galerie",
    "karte.galerie.text": "Regarde toutes les images que tu as déjà résolues.",
    "karte.burg.titel": "Construire un château",
    "karte.burg.text": "Dépense de l'or et bâtis ton château pierre par pierre.",
    "karte.hoehle.titel": "Grotte du dragon",
    "karte.hoehle.text": "Achète un œuf de dragon et élève ton propre dragon.",

    "rang.knappe": "Écuyer",
    "rang.ritter": "Chevalier",
    "rang.schatzmeister": "Trésorier",
    "rang.drachenreiter": "Chevaucheur de dragon",
    "rang.legende": "Légende",
    "rang.baron": "Baron",
    "rang.graf": "Comte",
    "rang.herzog": "Duc",
    "rang.fuerst": "Prince",
    "rang.koenig": "Roi",
    "rang.kaiser": "Empereur",
    "rang.drachentoeter": "Tueur de dragons",
    "rang.unsterblicher": "Immortel",
    "rang.gott.des.goldes": "Dieu de l'Or",
    "rang.fortschritt": "encore {n} jusqu'à {rang}",
    "rang.max": "Rang le plus haut atteint ! 🌠",
    "rang.neu": "Nouveau rang !",

    "drache.glutzahn": "Crocbraise",
    "drache.nebelschwinge": "Ailebrume",
    "drache.frostkralle": "Griffe de givre",
    "drache.schattenhorn": "Corne d'ombre",
    "drache.koenigsdrache": "Dragon Roi",

    "k.partei.ritter": "Chevalier",
    "k.runde": "Dragon {n}/{m}",
    "frage.zahl": "Quel nombre convient ?",
    "k.falsch": "La bonne réponse était : {loesung}",
    "k.falsch.gold": "La bonne réponse était : {loesung}  −{n} d'or",
    "k.win.titel": "{name} est vaincu !",
    "k.win.beute": "🪙 +{n} d'or, trésor du dragon",
    "k.win.text": "On continue : {name} attend déjà. Tes cœurs sont de nouveau pleins.",
    "k.ende.sieg.titel": "Tous les dragons sont vaincus !",
    "k.ende.sieg.text": "Le royaume est sauvé – et ton or est dans le trésor.",
    "k.ende.niederlage.titel": "Le dragon était plus fort",
    "k.ende.niederlage.text": "Tes cœurs sont épuisés. Ton or reste à toi – encore un essai ?",

    "lob.treffer": "Touché !",
    "lob.stark": "Fort !",
    "lob.volltreffer": "En plein mille !",
    "lob.genau": "Exactement !",
    "lob.perfekt": "Parfait !",
    "lob.super": "Super calcul !",

    "gold.plus": "+{n} d'or",

    "h.fast": "Presque ! {loesung} – encore une fois.",
    "h.fast.gold": "Presque ! {loesung}  −{n} d'or. Encore une fois.",
    "h.serie": "🔥 Série ! À partir de maintenant ×{n} d'or",
    "h.ziel.basis": { one: "{n} exercice réussi, meilleure série : {b}.", other: "{n} exercices réussis, meilleure série : {b}." },
    "h.ziel.sauber": "Et pas une seule erreur !",
    "h.weiterso": "Continue comme ça !",

    "puzzle.kaufen": "🧩 Acheter une pièce – {n} d'or",
    "puzzle.eins": "🧩 1 pièce de puzzle",
    "puzzle.rest": { one: "Il manque {n} pièce. Chaque achat révèle un peu plus.", other: "Il manque {n} pièces. Chaque achat révèle un peu plus." },
    "puzzle.brauchst": "Il te faut encore {n} d'or.",
    "puzzle.genug": "Tu as assez d'or – quelle pièce sera visible ensuite ?",
    "puzzle.alle.btn": "🏆 Toutes les images récoltées !",
    "puzzle.alle.text": "Bravo ! Tu as révélé chaque image en entier.",
    "puzzle.alle.hinweis": "Tu peux toutes les regarder dans la galerie.",
    "puzzle.geloest.btn": "🏆 Puzzle résolu !",
    "puzzle.geloest.text": "Bravo ! L'image est entièrement révélée.",
    "puzzle.geloest.hinweis": "Le puzzle suivant se prépare …",
    "puzzle.funken": "🎉 Puzzle résolu !",
    "puzzle.wandert": "Il part dans la galerie – la prochaine aventure attend !",
    "puzzle.alle.galerie": "Toutes les images sont maintenant dans ta galerie !",

    "galerie.titel": "🖼️ Ta galerie",
    "galerie.leer": "Aucune image finie – résous un puzzle et elle s'accrochera ici.",
    "galerie.alle": "Les {n} images récoltées ! Touche-en une.",
    "galerie.teile": { one: "{n} image sur {m} finie. Touche-la.", other: "{n} images sur {m} finies. Touche-en une." },
    "galerie.teile.kurz": "{n}/{m} pièces",
    "galerie.noch.zu": "fermé",
    "bild.titel": "Image {n}",
    "bild.hinweis": "Touche l'image pour la voir en plus grand.",
    "bild.zoom": "Fais glisser ton doigt sur l'image. Touche encore pour la rapetisser.",

    "burg.teil.mauer": "Mur",
    "burg.teil.rote-mauer": "Brique",
    "burg.teil.turmstein": "Pierre de tour",
    "burg.teil.tor": "Porte",
    "burg.teil.fenster": "Fenêtre",
    "burg.teil.dach": "Toit",
    "burg.teil.flagge": "Drapeau",
    "burg.teil.wappen": "Blason",
    "burg.teil.fackel": "Torche",
    "burg.teil.busch": "Buisson",
    "burg.teil.fass": "Tonneau",
    "burg.ziel.tor": "🚪 Porte",
    "burg.ziel.wappen": "🛡️ Blason",
    "burg.ziel.flagge": "🚩 Drapeau",
    "burg.ziel.mauern": "🧱 6 murs",
    "burg.waehle": "Choisis une pièce puis touche une case vide.",
    "burg.fehl": "Il te faut {n} d'or de plus pour {name}.",
    "burg.setzen": "Touche une case lumineuse pour poser {name}. Touche une pièce posée pour la démolir.",
    "burg.passt.nicht": "{name} ne va pas ici.",
    "burg.pracht": "🏰 Château magnifique ! Il est complet – tu peux continuer à l'agrandir.",
    "burg.abgerissen": "{name} démoli – +{n} d'or de retour.",
    "burg.feld": "Case {n}",
    "gekauft": "acheté",

    "hoehle.stufe.ei": "Œuf",
    "hoehle.stufe.schluepfling": "Dragonneau",
    "hoehle.stufe.jungdrache": "Jeune dragon",
    "hoehle.stufe.hausdrache": "Dragon de maison",
    "hoehle.text.ei": "Un œuf chaud repose dans la grotte. Nourris-le pour qu'il éclose.",
    "hoehle.text.schluepfling": "Il a éclos ! Un tout petit dragon te fait un clin d'œil.",
    "hoehle.text.jungdrache": "Il grandit – et vole maintenant à tes côtés au combat.",
    "hoehle.text.hausdrache": "Il a bien grandi ! Ton dragon est la fierté de la grotte.",
    "hoehle.schmuck.nest": "Nid",
    "hoehle.schmuck.fackel": "Torche",
    "hoehle.schmuck.gold": "Tas d'or",
    "hoehle.schmuck.kristall": "Cristal",
    "hoehle.schmuck.knochen": "Os",
    "hoehle.schmuck.stern": "Lumière d'étoiles",
    "hoehle.name.funkenschweif": "Queue-étincelle",
    "hoehle.name.glutherz": "Cœur de braise",
    "hoehle.name.mondschuppe": "Écaille de lune",
    "hoehle.name.sternenzahn": "Dent d'étoile",
    "hoehle.name.rauchwoelkchen": "Petit nuage",
    "hoehle.name.goldkralle": "Griffe d'or",
    "hoehle.ei.kaufen": "🥚 Acheter un œuf de dragon – {n} d'or",
    "hoehle.still": "La grotte est silencieuse. Ton propre dragon pourrait y vivre.",
    "hoehle.brauchst.ei": "Il te faut encore {n} d'or pour l'œuf.",
    "hoehle.genug.ei": "Tu as assez d'or – va chercher l'œuf !",
    "hoehle.ausgewachsen": "🐉 Il a grandi !",
    "hoehle.fertig": "Ton dragon a fini de grandir.",
    "hoehle.schmuecke": "Décore maintenant la grotte – il y sera bien.",
    "hoehle.fuettern": "🍖 Nourrir – {n} d'or",
    "hoehle.noch": "encore {n}× à nourrir jusqu'à {name}",
    "hoehle.brauchst.futter": "Il te faut encore {n} d'or pour la nourriture.",
    "hoehle.hunger": "Ton dragon a faim !",
    "hoehle.gewachsen": "🎉 Il a grandi ! C'est maintenant un {name}.",
    "hoehle.schmueckt": "{name} décore maintenant ta grotte.",
    "hoehle.hinweis.start": "Gagne de l'or dans les jeux de maths et anime la grotte.",
    "hoehle.name.titel": "Comment veux-tu appeler ton dragon ?",
    "hoehle.name.text": "Touche un nom \u2013 il restera pour toujours.",
    "hoehle.hunger.mehr": { one: "Ton dragon a besoin de {n} repas de plus.", other: "Ton dragon a besoin de {n} repas de plus." },
    "hoehle.farben.titel": "Couleur du dragon",
    "farbe.feuer": "Rouge feu",
    "farbe.wald": "Vert for\u00eat",
    "farbe.eis": "Bleu glace",
    "farbe.nacht": "Violet nuit",
    "farbe.gold": "Jaune d'or",
    "farbe.rosen": "Rose",
    "farbe.gesperrt": "encore {n} tours",
    "hunger.banner.titel": "Ton dragon a faim",
    "hunger.banner.text": "Direction la grotte pour le nourrir !",

    "m.frage": "Comble le trou lumineux du mur.",
    "m.rechne": "Calcule : {a} + {b}",
    "m.rechne.rueckwaerts": "À l'envers : {a} − {b}",
    "m.weiter": "Au trou suivant.",
    "m.falsch": "La bonne réponse était : {loesung}",
    "m.falsch.gold": "La bonne réponse était : {loesung}  −{n} d'or",
    "m.ziel.basis": { one: "{n} trou comblé, meilleure série : {b}.", other: "{n} trous comblés, meilleure série : {b}." },

    "t.gegner.blauhelm": "Chevalier Heaumeblue",
    "t.gegner.grauguss": "Comte Grisacier",
    "t.gegner.silberzahn": "Sire Dentargent",
    "t.gegner.goldhelm": "Roi Heaumedor",
    "t.dein.ritter": "Ton chevalier",
    "t.ritt": "Charge {n}/{m}",
    "t.aus.sattel": "{name} tombe de cheval !",
    "t.weiter.gegen": "Tu as réussi {n} coups – on continue contre {name}.",
    "t.staerker": "{name} était plus fort",
    "t.verloren": "Tu as résolu {n}, mais fait {m} erreurs. Encore un essai ?",
    "t.sieg": "Tournoi gagné !",
    "t.sieg.text": "Tous les chevaliers sont vaincus – {n} exercices résolus, meilleure série : {b}.",
    "t.daneben": "Raté ! {loesung}",
    "t.daneben.gold": "Raté ! {loesung}  −{n} d'or.",

    "turm.frage.hoch": "Encore autant \u2013 un barreau plus haut !",
    "turm.frage.runter": "Deux barreaux \u00e9gaux font celui du dessus.",
    "turm.gipfel": "En haut ! Voil\u00e0 le tr\u00e9sor.",
    "turm.unten.gold": "Coffre en or ! Pas une seule erreur.",
    "turm.unten.silber": "Coffre en argent \u2013 bravo !",
    "turm.abgerutscht": "Tu as gliss\u00e9 ! La r\u00e9ponse \u00e9tait : {loesung}",
    "turm.abgerutscht.gold": "Tu as gliss\u00e9 ! La r\u00e9ponse \u00e9tait : {loesung}  \u2212{n} or",
    "turm.halt": "La r\u00e9ponse \u00e9tait : {loesung} \u2013 tu restes sur ce barreau.",
    "turm.farbe.frei": "\ud83c\udfa8 Nouvelle couleur de dragon d\u00e9bloqu\u00e9e : {name} !",
    "turm.titel": "Toutes les tours gravies !",
    "turm.weiter": "Continuer \u00e0 grimper",
    "turm.ziel.basis": { one: "{n} barreau franchi, meilleure s\u00e9rie : {b}.", other: "{n} barreaux franchis, meilleure s\u00e9rie : {b}." },
    /* --- Tour de l\u2019horloge --- */
    "uhr": "Manche",
    "uhr.halb.bezug": "aktuelle",
    "uhr.form.voll": "{n} heures",
    "uhr.form.halb": "{n} heures et demie",
    "uhr.form.viertelnach": "{n} heures et quart",
    "uhr.form.viertelvor": "{n} heures moins le quart",
    "uhr.frage.ablesen": "Quelle heure est-il\u00a0?",
    "uhr.frage.zuordnen": "Quelle horloge le montre\u00a0?",
    "uhr.tipp.voll": "La petite aiguille dit l\u2019heure, la grande est sur le 12.",
    "uhr.tipp.halb": "La grande aiguille est sur le 6, un demi-tour d\u2019horloge.",
    "uhr.tipp.viertel": "La grande aiguille est sur le 3 ou sur le 9 \u2013 un quart d\u2019heure apr\u00e8s ou avant.",
    "uhr.glocke": "La cloche sonne\u00a0!",
    "uhr.falsch": "Il est {zeit}.",
    "uhr.falsch.gold": "Il est {zeit}.  \u2212{n} d\u2019or",
    "uhr.bonus.knopf": "\ud83d\udd14 Bonus\u00a0: les quarts",
    "uhr.bonus.start": "Manche bonus\u00a0! Voici les quarts d\u2019heure.",
    "uhr.titel": "L\u2019horloge de la tour repart\u00a0!",
    "uhr.weiter": "Encore une fois",
    "uhr.ziel.basis": { one: "{n} heure bien lue, meilleure s\u00e9rie\u00a0: {b}.", other: "{n} heures bien lues, meilleure s\u00e9rie\u00a0: {b}." },

    "truhe.titel": "Un coffre au trésor !",
    "truhe.text": "Touche le coffre.",
    "truhe.gefunden": "{name} trouvé !",
    "truhe.neu": "Nouveau dans ton trésor – {n} sur {m}.",
    "truhe.gold.voll": "Plein d'or !",
    "truhe.alle": "Tu as déjà tous les trésors – alors la caisse tinte.",
    "truhe.weiter": "Continuer à calculer",

    "kammer.titel": "Ton trésor",
    "kammer.text": { one: "{n} trésor sur {m} trouvé", other: "{n} trésors sur {m} trouvés" },
    "kammer.gesperrt": "🔒 Continue à jouer pour le trouver !",
    "kammer.noch.offen": "fermé",
    "kammer.neu": "NOUVEAU",
    "kammer.gold": "🪙 {n} d'or · {rang}",

    "konto.titel": "Qui joue ?",
    "konto.neu": "Nouvel enfant",
    "konto.neu.text": "Choisis une image et écris ton nom (ou laisse-le vide).",
    "konto.name.placeholder": "Ton nom (facultatif)",
    "konto.fertig": "Terminé",
    "konto.abbrechen": "Annuler",
    "konto.default.name": "Chevalier {n}",
    "sprache.titel": "Langue",

    "win.weiter": "Dragon suivant",
    "ende.nochmal": "Encore une fois",
    "ende.richtig": "correct",
    "ende.serie": "meilleure série",
    "ende.gold": "or gagné",

    "ziel.titel": "Objectif du jour atteint !",
    "ziel.weiter": "Continuer à récolter",
    "ziel.bonus": "+100 d'or bonus",
    "mauer.titel": "Tous les murs de nombres faits !",
    "mauer.weiter": "Continuer les murs",
    "turnier.weiter": "Continuer",

    "aria.antwort": "Réponse {n}",
    "aria.burgbaustelle": "Chantier du château",
    "aria.bauteile": "Pièces",
    "aria.hoehle.schmuck": "Décor de la grotte",
    "aria.mauer": "Mur de nombres",
    "aria.turm": "Tour du dragon",
    "aria.uhr": "Horloge de la tour",
    "aria.uhr.wahl": "Horloge {n}",
    "aria.puzzlebild": "Image du puzzle",
    "aria.bild.geloest": "Image de puzzle résolue"
  },

  tr: {
    "title": "Matematik Şövalyeleri – 20'ye kadar toplama ve çıkarma",
    "start.titel": "Matematik Şövalyeleri",
    "start.untertitel": "Matematik maceraya dönüşüyor",
    "wer.spielt": "Kim oynuyor?",
    "konto.tippe": "Resmine dokun.",
    "dein.rang": "Senin rütben",
    "frage.raum": "Nereye kadar sayalım?",
    "frage.art": "Ne çalışıyoruz?",
    "raum.bis10": "10'a kadar",
    "raum.bis20": "20'ye kadar",
    "art.plus": "sadece toplama",
    "art.beides": "toplama ve çıkarma",
    "wahl.ausgewaehlt": "✓ seçildi",
    "konto.du.bist.dran": "✓ sıra sende",
    "spielen.verdienen": "🎯 Oyna & Kazan",
    "gold.ausgeben": "🪙 Altın harca",
    "badge.verdienen": "Kazan",
    "badge.ausgeben": "Harca",
    "badge.ansehen": "Bak",
    "ton.an": "🔊 Ses açık",
    "ton.aus": "🔇 Ses kapalı",
    "ton.kurz": "🔊 Ses",
    "heim": "🏠 Ana sayfa",
    "kammer": "🗝️ Hazine",
    "tipp": "💡 İpucu",
    "gold": "Altın",
    "serie": "Seri",
    "aufgabe": "Görev",
    "puzzle": "Yapboz",
    "teile": "Parça",
    "mauer": "Duvar",
    "turm": "Kule",
    "gegner": "Rakip",
    "futter": "Yem",
    "drache": "Ejderha",
    "burgwert": "Kale değeri",
    "bilder": "Resimler",
    "zurueck": "Geri",

    "schatz.diamant": "Elmas",
    "schatz.krone": "Taç",
    "schatz.schluessel": "Altın anahtar",
    "schatz.stab": "Sihirli değnek",
    "schatz.schwert": "Alev kılıcı",
    "schatz.schild": "Gümüş kalkan",
    "schatz.ei": "Ejderha yumurtası",
    "schatz.einhorn": "Tek boynuzlu at",
    "schatz.kompass": "Pusula",
    "schatz.laterne": "Sonsuz ışık",
    "schatz.vase": "Altın vazo",
    "schatz.perle": "Gökkuşağı incisi",
    "galerie.kurz": "🖼️ Galeri",
    "puzzle.kurz": "🧩 Yapboz",

    "karte.kampf.titel": "Şövalyeler Ejderhalara Karşı",
    "karte.kampf.text": "Ejderhanın dişlerini sök. Her isabet altın kazandırır.",
    "karte.hort.titel": "Hazine avı",
    "karte.hort.text": "Rahatça altın topla – can yok, kaybetmek yok.",
    "karte.mauer.titel": "Sayı duvarı",
    "karte.mauer.text": "Duvarın boşluklarını doldur ve altın kazan.",
    "karte.turnier.titel": "Şövalye turnuvası",
    "karte.turnier.text": "Mızrağınla saldır ve rakibe kadar çöz.",
    "karte.turm.titel": "Ejderha kulesi",
    "karte.turm.text": "Merdivenden hazineye t\u0131rman \u2013 sonra geri in.",
    "karte.uhr.titel": "Saat kulesi",
    "karte.uhr.text": "Kule saatini oku, \u00e7an yeniden \u00e7als\u0131n.",
    "karte.puzzle.titel": "Yapboz hazinesi",
    "karte.puzzle.text": "200 altına parça al ve resmi parça parça ortaya çıkar.",
    "karte.galerie.titel": "Galeri",
    "karte.galerie.text": "Çözdüğün bütün resimlere bak.",
    "karte.burg.titel": "Kale yap",
    "karte.burg.text": "Altın harca ve kaleni taş taş inşa et.",
    "karte.hoehle.titel": "Ejderha mağarası",
    "karte.hoehle.text": "Bir ejderha yumurtası al ve kendi ejderhanı büyüt.",

    "rang.knappe": "Silahşor",
    "rang.ritter": "Şövalye",
    "rang.schatzmeister": "Hazinedar",
    "rang.drachenreiter": "Ejderha binicisi",
    "rang.legende": "Efsane",
    "rang.baron": "Baron",
    "rang.graf": "Kont",
    "rang.herzog": "Dük",
    "rang.fuerst": "Prens",
    "rang.koenig": "Kral",
    "rang.kaiser": "İmparator",
    "rang.drachentoeter": "Ejderha avcısı",
    "rang.unsterblicher": "Ölümsüz",
    "rang.gott.des.goldes": "Altının Tanrısı",
    "rang.fortschritt": "{rang} olmak için {n} kaldı",
    "rang.max": "En yüksek rütbeye ulaşıldı! 🌠",
    "rang.neu": "Yeni rütbe!",

    "drache.glutzahn": "Kor Diş",
    "drache.nebelschwinge": "Sis Kanat",
    "drache.frostkralle": "Don Pençe",
    "drache.schattenhorn": "Gölge Boynuz",
    "drache.koenigsdrache": "Kral Ejderha",

    "k.partei.ritter": "Şövalye",
    "k.runde": "Ejderha {n}/{m}",
    "frage.zahl": "Hangi sayı uyuyor?",
    "k.falsch": "Doğrusu şuydu: {loesung}",
    "k.falsch.gold": "Doğrusu şuydu: {loesung}  −{n} altın",
    "k.win.titel": "{name} yenildi!",
    "k.win.beute": "🪙 +{n} altın ejderha hazinesi",
    "k.win.text": "Devam ediyoruz: {name} bekliyor. Canların yine dolu.",
    "k.ende.sieg.titel": "Bütün ejderhalar yenildi!",
    "k.ende.sieg.text": "Krallık kurtarıldı – ejderha altının hazinede.",
    "k.ende.niederlage.titel": "Ejderha daha güçlüydü",
    "k.ende.niederlage.text": "Canların bitti. Altının sende kalıyor – bir kez daha dene?",

    "lob.treffer": "İsabet!",
    "lob.stark": "Güçlü!",
    "lob.volltreffer": "Tam isabet!",
    "lob.genau": "Aynen doğru!",
    "lob.perfekt": "Mükemmel!",
    "lob.super": "Harika hesap!",

    "gold.plus": "+{n} altın",

    "h.fast": "Yaklaştın! {loesung} – bir daha dene.",
    "h.fast.gold": "Yaklaştın! {loesung}  −{n} altın. Bir daha dene.",
    "h.serie": "🔥 Seri! Artık ×{n} altın",
    "h.ziel.basis": { one: "{n} görev yapıldı, en iyi seri: {b}.", other: "{n} görev yapıldı, en iyi seri: {b}." },
    "h.ziel.sauber": "Ve tek bir hata bile yok!",
    "h.weiterso": "Böyle devam!",

    "puzzle.kaufen": "🧩 Parça satın al – {n} altın",
    "puzzle.eins": "🧩 1 yapboz parçası",
    "puzzle.rest": { one: "{n} parça eksik. Her alışta biraz daha görünür.", other: "{n} parça eksik. Her alışta biraz daha görünür." },
    "puzzle.brauchst": "Hâlâ {n} altına ihtiyacın var.",
    "puzzle.genug": "Yeterince altının var – sıradaki hangi parça görünecek?",
    "puzzle.alle.btn": "🏆 Bütün resimler toplandı!",
    "puzzle.alle.text": "Aferin! Her resmi tamamen ortaya çıkardın.",
    "puzzle.alle.hinweis": "Hepsine galeride bakabilirsin.",
    "puzzle.geloest.btn": "🏆 Yapboz çözüldü!",
    "puzzle.geloest.text": "Aferin! Resim tamamen göründü.",
    "puzzle.geloest.hinweis": "Sıradaki yapboz hazırlanıyor …",
    "puzzle.funken": "🎉 Yapboz çözüldü!",
    "puzzle.wandert": "Galeriye gidiyor – sıradaki macera bekliyor!",
    "puzzle.alle.galerie": "Bütün resimler artık galerinde!",

    "galerie.titel": "🖼️ Senin galerin",
    "galerie.leer": "Henüz hiçbir resim bitmedi – bir yapboz çöz, burada asılsın.",
    "galerie.alle": "{n} resim toplandı! Birine dokun.",
    "galerie.teile": { one: "{m} resimden {n}'i bitti. Ona dokun.", other: "{m} resimden {n}'i bitti. Birine dokun." },
    "galerie.teile.kurz": "{n}/{m} parça",
    "galerie.noch.zu": "kapalı",
    "bild.titel": "Resim {n}",
    "bild.hinweis": "Daha büyük görmek için resme dokun.",
    "bild.zoom": "Parmağını resmin üzerinde kaydır. Tekrar dokunursan küçülür.",

    "burg.teil.mauer": "Duvar",
    "burg.teil.rote-mauer": "Tuğla",
    "burg.teil.turmstein": "Kule taşı",
    "burg.teil.tor": "Kapı",
    "burg.teil.fenster": "Pencere",
    "burg.teil.dach": "Çatı",
    "burg.teil.flagge": "Bayrak",
    "burg.teil.wappen": "Arma",
    "burg.teil.fackel": "Meşale",
    "burg.teil.busch": "Çalı",
    "burg.teil.fass": "Varil",
    "burg.ziel.tor": "🚪 Kapı",
    "burg.ziel.wappen": "🛡️ Arma",
    "burg.ziel.flagge": "🚩 Bayrak",
    "burg.ziel.mauern": "🧱 6 duvar",
    "burg.waehle": "Bir parça seç ve boş bir kareye dokun.",
    "burg.fehl": "{name} için {n} altına daha ihtiyacın var.",
    "burg.setzen": "Parlayan kareye dokunarak {name} koy. Koyulmuş bir parçaya dokunursan sökülür.",
    "burg.passt.nicht": "{name} buraya sığmaz.",
    "burg.pracht": "🏰 Muhteşem kale! Tamamlandı – genişletmeye devam edebilirsin.",
    "burg.abgerissen": "{name} söküldü – +{n} altın geri.",
    "burg.feld": "Kare {n}",
    "gekauft": "alındı",

    "hoehle.stufe.ei": "Yumurta",
    "hoehle.stufe.schluepfling": "Yavru",
    "hoehle.stufe.jungdrache": "Genç ejderha",
    "hoehle.stufe.hausdrache": "Ev ejderhası",
    "hoehle.text.ei": "Mağarada sıcak bir yumurta var. Çatlaması için onu besle.",
    "hoehle.text.schluepfling": "Çatladı! Minicik bir ejderha sana göz kırpıyor.",
    "hoehle.text.jungdrache": "Büyüyor – ve artık ejderha savaşlarında yanında uçuyor.",
    "hoehle.text.hausdrache": "Büyüdü! Ejderhan mağaranın gururu.",
    "hoehle.schmuck.nest": "Yuva",
    "hoehle.schmuck.fackel": "Meşale",
    "hoehle.schmuck.gold": "Altın yığını",
    "hoehle.schmuck.kristall": "Kristal",
    "hoehle.schmuck.knochen": "Kemik",
    "hoehle.schmuck.stern": "Yıldız ışığı",
    "hoehle.name.funkenschweif": "Kıvılcım Kuyruk",
    "hoehle.name.glutherz": "Kor Yürek",
    "hoehle.name.mondschuppe": "Ay Pulu",
    "hoehle.name.sternenzahn": "Yıldız Diş",
    "hoehle.name.rauchwoelkchen": "Duman Bulutu",
    "hoehle.name.goldkralle": "Altın Pençe",
    "hoehle.ei.kaufen": "🥚 Ejderha yumurtası al – {n} altın",
    "hoehle.still": "Mağara sessiz. Kendi ejderhan burada yaşayabilir.",
    "hoehle.brauchst.ei": "Yumurta için hâlâ {n} altına ihtiyacın var.",
    "hoehle.genug.ei": "Yeterince altının var – git yumurtayı al!",
    "hoehle.ausgewachsen": "🐉 Büyüdü!",
    "hoehle.fertig": "Ejderhanın büyümesi bitti.",
    "hoehle.schmuecke": "Şimdi mağarayı süsle – orada rahat edecek.",
    "hoehle.fuettern": "🍖 Besle – {n} altın",
    "hoehle.noch": "{name} olmak için {n}× daha besle",
    "hoehle.brauchst.futter": "Yem için hâlâ {n} altına ihtiyacın var.",
    "hoehle.hunger": "Ejderhan acıktı!",
    "hoehle.gewachsen": "🎉 Büyüdü! Artık bir {name}.",
    "hoehle.schmueckt": "{name} artık mağaranı süslüyor.",
    "hoehle.hinweis.start": "Matematik oyunlarında altın kazan ve mağaraya hayat getir.",
    "hoehle.name.titel": "Ejderhan\u0131n ad\u0131 ne olsun?",
    "hoehle.name.text": "Bir isme dokun \u2013 sonsuza dek kal\u0131r.",
    "hoehle.hunger.mehr": { one: "Ejderhan {n} \u00f6\u011f\u00fcn daha istiyor.", other: "Ejderhan {n} \u00f6\u011f\u00fcn daha istiyor." },
    "hoehle.farben.titel": "Ejderha rengi",
    "farbe.feuer": "Ate\u015f k\u0131rm\u0131z\u0131s\u0131",
    "farbe.wald": "Orman ye\u015fili",
    "farbe.eis": "Buz mavisi",
    "farbe.nacht": "Gece moru",
    "farbe.gold": "Alt\u0131n sar\u0131s\u0131",
    "farbe.rosen": "G\u00fcl pembesi",
    "farbe.gesperrt": "{n} kule daha",
    "hunger.banner.titel": "Ejderhan a\u00e7",
    "hunger.banner.text": "Ma\u011faraya git ve besle!",

    "m.frage": "Duvarın parlayan boşluğunu doldur.",
    "m.rechne": "Hesapla: {a} + {b}",
    "m.rechne.rueckwaerts": "Geriye doğru: {a} − {b}",
    "m.weiter": "Sıradaki boşluğa.",
    "m.falsch": "Doğrusu şuydu: {loesung}",
    "m.falsch.gold": "Doğrusu şuydu: {loesung}  −{n} altın",
    "m.ziel.basis": { one: "{n} boşluk dolduruldu, en iyi seri: {b}.", other: "{n} boşluk dolduruldu, en iyi seri: {b}." },

    "t.gegner.blauhelm": "Şövalye Mavimiğfer",
    "t.gegner.grauguss": "Kont Griçelik",
    "t.gegner.silberzahn": "Sör Gümüşdiş",
    "t.gegner.goldhelm": "Kral Altınmiğfer",
    "t.dein.ritter": "Senin şövalyen",
    "t.ritt": "Akın {n}/{m}",
    "t.aus.sattel": "{name} eyerden düştü!",
    "t.weiter.gegen": "{n} isabet vurdun – {name}'e karşı devam ediyoruz.",
    "t.staerker": "{name} daha güçlüydü",
    "t.verloren": "{n} çözdün ama {m} hata yaptın. Bir kez daha dene?",
    "t.sieg": "Turnuva kazanıldı!",
    "t.sieg.text": "Bütün şövalyeler yenildi – {n} görev çözüldü, en iyi seri: {b}.",
    "t.daneben": "Kaçırdın! {loesung}",
    "t.daneben.gold": "Kaçırdın! {loesung}  −{n} altın.",

    "turm.frage.hoch": "Bir o kadar daha \u2013 bir basamak yukar\u0131!",
    "turm.frage.runter": "\u0130ki e\u015fit basamak \u00fcsttekini olu\u015fturur.",
    "turm.gipfel": "Zirvede! Hazine orada.",
    "turm.unten.gold": "Alt\u0131n sand\u0131k! Tek bir hata bile yok.",
    "turm.unten.silber": "G\u00fcm\u00fc\u015f sand\u0131k \u2013 ba\u015fard\u0131n!",
    "turm.abgerutscht": "Kayd\u0131n! Do\u011frusu: {loesung}",
    "turm.abgerutscht.gold": "Kayd\u0131n! Do\u011frusu: {loesung}  \u2212{n} alt\u0131n",
    "turm.halt": "Do\u011frusu: {loesung} \u2013 bu basamakta kal\u0131yorsun.",
    "turm.farbe.frei": "\ud83c\udfa8 Yeni ejderha rengi a\u00e7\u0131ld\u0131: {name}!",
    "turm.titel": "B\u00fct\u00fcn kuleler t\u0131rmand\u0131!",
    "turm.weiter": "T\u0131rmanmaya devam",
    "turm.ziel.basis": { one: "{n} basamak tamam, en iyi seri: {b}.", other: "{n} basamak tamam, en iyi seri: {b}." },
    /* --- Saat kulesi --- */
    "uhr": "Tur",
    "uhr.halb.bezug": "aktuelle",
    "uhr.form.voll": "saat {n}",
    "uhr.form.halb": "{n} bu\u00e7uk",
    "uhr.form.viertelnach": "{n} \u00e7eyrek ge\u00e7e",
    "uhr.form.viertelvor": "{n} \u00e7eyrek kala",
    "uhr.frage.ablesen": "Saat ka\u00e7?",
    "uhr.frage.zuordnen": "Hangi saat bunu g\u00f6steriyor?",
    "uhr.tipp.voll": "K\u00fc\u00e7\u00fck ibre saati s\u00f6yler, b\u00fcy\u00fck ibre 12\u2019yi g\u00f6sterir.",
    "uhr.tipp.halb": "B\u00fcy\u00fck ibre 6\u2019y\u0131 g\u00f6steriyor, saatin yar\u0131s\u0131.",
    "uhr.tipp.viertel": "B\u00fcy\u00fck ibre 3\u2019\u00fc ya da 9\u2019u g\u00f6steriyor \u2013 tam saatten \u00e7eyrek sonra ya da \u00f6nce.",
    "uhr.glocke": "\u00c7an \u00e7al\u0131yor!",
    "uhr.falsch": "Saat {zeit}.",
    "uhr.falsch.gold": "Saat {zeit}.  \u2212{n} alt\u0131n",
    "uhr.bonus.knopf": "\ud83d\udd14 Bonus: \u00e7eyrekler",
    "uhr.bonus.start": "Bonus tur! \u015eimdi \u00e7eyrek saatler.",
    "uhr.titel": "Kule saati yine i\u015fliyor!",
    "uhr.weiter": "Bir kez daha",
    "uhr.ziel.basis": { one: "{n} saat do\u011fru okundu, en iyi seri: {b}.", other: "{n} saat do\u011fru okundu, en iyi seri: {b}." },

    "truhe.titel": "Bir hazine sandığı!",
    "truhe.text": "Sandığa dokun.",
    "truhe.gefunden": "{name} bulundu!",
    "truhe.neu": "Hazinende yeni – {m} taneden {n}. tanesi.",
    "truhe.gold.voll": "Ağzına kadar altın!",
    "truhe.alle": "Bütün hazineler sende – o yüzden kasa çalıyor.",
    "truhe.weiter": "Hesaplamaya devam",

    "kammer.titel": "Senin hazinen",
    "kammer.text": { one: "{m} hazineden {n}'i bulundu", other: "{m} hazineden {n}'i bulundu" },
    "kammer.gesperrt": "🔒 Onu bulmak için oynamaya devam et!",
    "kammer.noch.offen": "kapalı",
    "kammer.neu": "YENİ",
    "kammer.gold": "🪙 {n} altın · {rang}",

    "konto.titel": "Kim oynuyor?",
    "konto.neu": "Yeni çocuk",
    "konto.neu.text": "Bir resim seç ve adını yaz (ya da boş bırak).",
    "konto.name.placeholder": "Adın (isteğe bağlı)",
    "konto.fertig": "Bitti",
    "konto.abbrechen": "Vazgeç",
    "konto.default.name": "Şövalye {n}",
    "sprache.titel": "Dil",

    "win.weiter": "Sonraki ejderha",
    "ende.nochmal": "Bir kez daha",
    "ende.richtig": "doğru",
    "ende.serie": "en iyi seri",
    "ende.gold": "kazanılan altın",

    "ziel.titel": "Günlük hedefe ulaşıldı!",
    "ziel.weiter": "Toplamaya devam",
    "ziel.bonus": "+100 bonus altın",
    "mauer.titel": "Bütün sayı duvarları bitti!",
    "mauer.weiter": "Duvarlara devam",
    "turnier.weiter": "Devam et",

    "aria.antwort": "Cevap {n}",
    "aria.burgbaustelle": "Kale şantiyesi",
    "aria.bauteile": "Parçalar",
    "aria.hoehle.schmuck": "Mağara süsleri",
    "aria.mauer": "Sayı duvarı",
    "aria.turm": "Ejderha kulesi",
    "aria.uhr": "Kule saati",
    "aria.uhr.wahl": "Saat {n}",
    "aria.puzzlebild": "Yapboz resmi",
    "aria.bild.geloest": "Çözülmüş yapboz resmi"
  }
};

let currentLang = "de";

function lang(){ return currentLang; }

function dict(code){ return I18N[code] || I18N.de || {}; }

function fill(s, vars){
  if(!vars) return s;
  return String(s).replace(/\{(\w+)\}/g, (m, k) => (k in vars) ? vars[k] : m);
}

function tr(key, vars){
  let s = dict(lang())[key];
  if(s === undefined) s = I18N.de[key];
  if(s === undefined) return key;
  if(typeof s === "object") s = s.other;
  return fill(s, vars);
}

/* Plural: {one, other}. n bestimmt die Form; {n} steht immer zur Verfügung. */
function trp(key, n, vars){
  const d = dict(lang());
  let e = d[key];
  if(e === undefined) e = I18N.de[key];
  if(e === undefined) return key;
  const form = (typeof e === "object") ? (n === 1 ? e.one : e.other) : e;
  return fill(form, Object.assign({}, vars, { n: n }));
}

function i18nAnwenden(){
  document.querySelectorAll("[data-i18n]").forEach(el => {
    el.textContent = tr(el.getAttribute("data-i18n"));
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    el.setAttribute("placeholder", tr(el.getAttribute("data-i18n-placeholder")));
  });
  document.querySelectorAll("[data-i18n-aria]").forEach(el => {
    el.setAttribute("aria-label", tr(el.getAttribute("data-i18n-aria")));
  });
  document.querySelectorAll("[data-i18n-alt]").forEach(el => {
    el.setAttribute("alt", tr(el.getAttribute("data-i18n-alt")));
  });
}

function setLang(code){
  if(SPRACHEN.indexOf(code) < 0) code = "de";
  currentLang = code;
  document.documentElement.lang = code;
  document.title = tr("title");
  /* Die zwei CSS-content-Texte laufen über Variablen. */
  document.documentElement.style.setProperty("--t-ausgewaehlt", JSON.stringify(tr("wahl.ausgewaehlt")));
  document.documentElement.style.setProperty("--t-du-bist-dran", JSON.stringify(tr("konto.du.bist.dran")));
  i18nAnwenden();
}

/* Standardsprache des Browsers auf eine der unterstützten Sprachen abbilden. */
function browserSprache(){
  const roh = (navigator.language || navigator.userLanguage || "de").toLowerCase();
  const code = roh.split("-")[0];
  return SPRACHEN.indexOf(code) >= 0 ? code : "de";
}
